#encoding: utf-8

commmon: &common
  adapter: mysql2
  encoding: utf8
  collation: utf8_danish_ci
  reconnect: true
  pool: 15
  host: 127.0.0.1
  socket: /tmp/mysql.sock

development:
  database: kinder_development
  username: root
  password:
  <<: *common

test: &test
  database: kinder_test
  username: root
  password:
  <<: *common

staging:
  database: kinder_staging
  username: root
  password: alfie
  <<: *common

production:
    database: rvo_production
    username: rvo
    password: alfie
    <<: *common